### PR TITLE
Replace the URL  dialog with a set of controls in the main dialog for a better handling of errors

### PR DESCRIPTION
**Pull request by nvdaes**
## Link to issue number:
Fixes issue #10
### Summary of the issue:
When an URL cannot be created, the reason is not notified to the user.
### Description of how this pull request fixes the issue:
* The NEW URL modal dialog is replaced with controls to provide the new URL, name, custom URL and a buttom to shorten.
* When known errors can be fixed, the focus should be placed in the corresponding input field.
* If an exception is raised, an error dialog should be presented showing the error, though I have never reproduced it.
### Testing performed:
Tested locally with different custom URLS,with and without a display name, and unplugging wifi.
### Known issues with pull request:
None.
### Change log entry:
* The new URL dialog has been replaced with a set of controls in the main dialog, so that the focus can be placed in the relevant field to fix possible errors.

### CODE REVIEW

**Comment by nvdaes** [comment]
This PR maybe merged tomorrow, in case someone wants to provide feedback before.
After merging, a beta version for further testing will be published on the store.

**Comment by XLTechie** [comment]
@nvdaes if you need to duplicate the original error, put something like a short add-on name-version as the custom URL.

```
URL: https://github.com/opensourcesys/numpadNavMode/releases/download/v23.1.1/numpadNavMode-23.1.1.nvda-addon
Name: Numpad Nav 23.1.1
Custom URL: NPNav-23.1.1
```

**Comment by nvdaes** [comment]
Thanks @XLTechie . Now we get an ui.message reporting that this custom URL is not available. Try with a different subfix. and the Custom URL field is focused so we can try with a different custom URL.

**Comment by XLTechie** [comment]
Sorry @nvdaes, for forgetting to comment about this until your reminder on the mailing list.

Two little things I noticed.

When I tried to create a URL with a bad custom part, this is what happened (captured through [Speech Logger](https://addons.nvda-project.org/addons/speechLogger.en.html)):

```
Shorten New URL  button  Alt+e
space
pressed
Custom URL  edit  Alt+t  selected addon-store-submit
This custom URL is not available. Try with a different subfix.
```

1. "subfix" is not a word in English. Maybe you meant "suffix"? I might just say "Try a different one".
2. The error is announced *after* the focus moves back to the field with the error. I think it would be better if the error could be read first, then the focus moved. I haven't looked at the code to know if that is possible, but I think it would be a better UX if so.

**Comment by nvdaes** [comment]
Replying to @XLTechie 👍 
> 1. "subfix" is not a word in English. Maybe you meant "suffix"? I might just say "Try a different one.

Oh,yes. I mean suffix, but I'll use Try a different

> 2. The error is announced after the focus moves back to the field with the error. I think it would be better if the error could be read first, then the focus moved. I haven't looked at the code to know if that is possible, but I think it would be a better UX if so.

I'll try to do it if possible, al in a stable version.

**Comment by XLTechie** [comment]
> Oh,yes. I mean suffix, but I'll use Try a different

"Try a different one."

**Comment by nvdaes** [comment]
Thanks Luke. I edited my comment. Hope the Try a different one
sentence has been reflected.

2023-05-05 9:47 GMT+02:00, Luke Davis ***@***.***>:

**Pull request merged**
